name: ${COMPOSE_PROJECT_NAME}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:1.0.0
    container_name: myapp
    ports:
      - "${PORT:-5000}:5000"
    environment:
      PORT: ${PORT:-5000}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MYSQL_URL: ${MYSQL_URL}
    command: >
      sh -c "
        npm run prisma:deploy
        npm run start:prod
      "
    restart: no
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - backend

networks:
  backend:
    driver: bridge