services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME:-myapp}:1.0
    container_name: ${COMPOSE_PROJECT_NAME:-myapp}_app
    ports:
      - "${PORT:-5000}:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MYSQL_URL: ${MYSQL_DOCKER_URL}
    command: >
      sh -c "
        npm run prisma:deploy
        npm run prisma:generate
        npm run start:prod
      "
    restart: no
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    networks:
      - backend
  redis:
    image: redis:${REDIS_VERSION:-7.2}
    container_name: ${COMPOSE_PROJECT_NAME:-myapp}_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: > 
      redis-server 
      --appendonly yes 
      --protected-mode yes 
      --requirepass "${REDIS_PASSWORD}" 
      --bind 0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "auth", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - backend
volumes:
  redis_data:

networks:
  backend:
    driver: bridge